## These functions make it possible to create a special matrix that
## can cache its inverse. The makeCacheMatrix function uses features 
## of R to cache the inverse in a specific environment, and the 
## cacheSolve function is responsible for actually calculating 
## (and caching) the inverse.
##
## EXAMPLE:
##   mat <- matrix(c(2,2,3,2), nrow = 2, ncol = 2)
##   m <- makeCacheMatrix(mat)
##   cacheSolve(m)
##   (outputs inverse)
##   cacheSolve(m)
##   (outputs inverse from cache)


## The makeCacheMatrix takes a square invertible matrix as input,
## and returns a special 'matrix' that can cache its inverse.
## This is done by returning a list of functions that work in an 
## environment specific for this object.
##
## USAGE: makeCacheMatrix(x) - where 'x' is an R matrix. 
makeCacheMatrix <- function(x = matrix()) {
  i <- NULL # initialize non-computed inverse
  set <- function(y) {
    x <<- y
    i <<- NULL # reset inverse, so cacheSolve will recompute
  }
  get <- function() x
  setinverse <- function(inverse) i <<- inverse
  getinverse <- function() i
  list(set = set, get = get, 
       getinverse = getinverse, 
       setinverse = setinverse)
}


## cacheSolve takes as input a special matrix, generated by 
## makeCacheMatrix and returns the inverse. It is a cached 
## version of the solve function. It checks if the inverse
## is already cached in the special environment of the matrix,
## and only computes the inverse, if it is not already present.
##
## USAGE: cacheSolve(x, ...) - where 'x' is an object returned by
##                             the 'makeCacheMatrix' function.
##
cacheSolve <- function(x, ...) {
  i <- x$getinverse() # tries to retrieve from cache
  if (!is.null(i)) {
    # reached if the inverse was cached
    message("getting cached data")
    return(i)
  }
  # only reached if inverse was not cached
  data <- x$get()
  i <- solve(data)
  x$setinverse(i)
  i
}
